name: report
author: NamelessLeaf
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
main: NamelessLeaf/report
version: 1.0
description: Report system for MCPE 
commands: 
  report:
    description: Report a player
permission:
  report.recive:
    default: op
